"""
🦈 Shark Calendar - Auto Event Worker
Creates a random event on a far-off date every 10-20 minutes.
Deletes worker-created events every 5 minutes.

Requires: supabase
Install:  pip install supabase python-dotenv
Usage:    python shark_event_worker.py
"""

import os
import json
import random
import asyncio
import logging
from datetime import datetime, date
from typing import Optional

# ── Try python-dotenv, fall back to manual loader ──────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    def load_dotenv():  # noqa
        if not os.path.exists(".env"):
            return
        with open(".env") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))
    load_dotenv()

from supabase import create_client, Client

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("SharkWorker")

# ── Config ─────────────────────────────────────────────────────────────────────
EVENTS_TABLE   = "shark_events"
WORKER_TAG     = "[WORKER]"          # Prefix added to every worker-created event title
                                     # — used to identify which events to clean up.

CREATE_MIN_SEC = 10 * 60             # 10 minutes  (minimum gap between creations)
CREATE_MAX_SEC = 20 * 60             # 20 minutes  (maximum gap between creations)
DELETE_SEC     = 5  * 60             # 5  minutes  (how often the cleanup runs)

# PostgreSQL / Python max date is 9999-12-31
FAR_DATE       = date(9999, 12, 31)

# ── Flavour pools ──────────────────────────────────────────────────────────────
EVENT_NAMES = [
    "Deep-Sea Expedition Briefing",
    "Apex Shark Summit 9999",
    "Final Oceanic Council",
    "Mega Migration Tracking",
    "Ultimate Feeding Frenzy Prep",
    "End-of-Timeline Team Sync",
    "Last Dive of the Millennium",
    "Tectonic Plate Watch Party",
    "Shark Week 9999 Kickoff",
    "Omega Migration Debrief",
    "Heat Death Calendar Block",
    "Neptunian Conference Call",
    "Abyssal Zone Check-In",
    "Final Reckoning Sprint Review",
    "Triassic Reunion Planning",
]

DESCRIPTIONS = [
    "A mandatory all-hands deep beneath the thermocline. Attendance compulsory for all apex predators.",
    "Reserved this slot before the sun expands. Better safe than sorry.",
    "Yearly sync pushed to the absolute limit of the calendar system.",
    "Block booked at the edge of recorded time to avoid scheduling conflicts.",
    "Our most ambitious planning session — set a reminder approximately 7,978 years in advance.",
    "Last known available slot. All other millennia are fully booked.",
    "Auto-generated by the Shark Calendar worker. Do not delete. (You can delete it.)",
    "Blocking time for the inevitable final migration. Snacks TBD.",
    "Recurring anchor event at the heat-death of the Gregorian calendar.",
    "Strategic planning for the species' 500-millionth birthday celebrations.",
]

LOCATIONS = [
    "The Mariana Trench, Pacific Ocean",
    "Challenger Deep — Breakout Room B",
    "Mid-Atlantic Ridge, Zoom Link TBD",
    "International Waters (unspecified)",
    "Sunken City of Atlantis",
    "Cloud Reef Conference Centre",
    "The Void (lat/lng pending)",
    "Somewhere in the Hadal Zone",
]

TAGS_POOL = [
    ["Coding Project"],
    ["Gaming"],
    ["Personal"],
    ["Work"],
    ["Stream"],
    ["Video"],
    ["University"],
    ["College Assignment"],
    ["Personal", "Gaming"],
    ["Work", "Coding Project"],
]

PLATFORMS_POOL = [
    [],
    ["Discord"],
    ["GitHub"],
    ["Teams"],
    ["YouTube", "Twitch"],
    ["Steam"],
    ["Discord", "Twitch"],
    ["GitHub", "Teams"],
]


# ── DB helpers ─────────────────────────────────────────────────────────────────

def get_client() -> Client:
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_KEY", "")
    pooler = os.environ.get("SUPABASE_POOLER_URL", "")
    username = os.environ.get("USER", "worker")

    if not url or not key:
        raise EnvironmentError(
            "SUPABASE_URL and SUPABASE_KEY must be set (in .env or environment)."
        )

    conn = pooler if pooler else url
    log.info("🔗  Connecting to Supabase (%s)…", "pooler" if pooler else "direct")
    return create_client(conn, key), username


def build_event(username: str) -> dict:
    """Return a dict matching the shark_events schema."""
    tags      = random.choice(TAGS_POOL)
    platforms = random.choice(PLATFORMS_POOL)

    return {
        "title":            f"{WORKER_TAG} {random.choice(EVENT_NAMES)}",
        "description":      random.choice(DESCRIPTIONS),
        "event_date":       str(FAR_DATE),          # "9999-12-31"
        "event_time":       None,
        "location":         random.choice(LOCATIONS),
        "tags":             json.dumps(tags),
        "platforms":        json.dumps(platforms),
        "notify_enabled":   False,
        "notify_days_before": 0,
        "repeat_enabled":   False,
        "repeat_interval":  None,
        "username":         username,
        "created_at":       datetime.now().isoformat(),
    }


# ── Worker tasks ───────────────────────────────────────────────────────────────

async def creator_task(client: Client, username: str) -> None:
    """Every 10-20 minutes: insert one random far-future event."""
    while True:
        wait = random.randint(CREATE_MIN_SEC, CREATE_MAX_SEC)
        log.info("⏳  Next event creation in %.1f min…", wait / 60)
        await asyncio.sleep(wait)

        event = build_event(username)
        try:
            result = client.table(EVENTS_TABLE).insert(event).execute()
            if result.data:
                created = result.data[0]
                log.info(
                    "✅  Created event #%s  »%s«  on %s",
                    created.get("id", "?"),
                    created.get("title", "?"),
                    created.get("event_date", "?"),
                )
            else:
                log.warning("⚠️   Insert returned no data: %s", result)
        except Exception as exc:
            log.error("❌  Failed to create event: %s", exc)


async def cleaner_task(client: Client, username: str) -> None:
    """Every 5 minutes: delete all worker-created events for this user."""
    while True:
        await asyncio.sleep(DELETE_SEC)
        log.info("🗑️   Running cleanup for user '%s'…", username)

        try:
            # Fetch IDs of every worker event belonging to this user
            result = (
                client.table(EVENTS_TABLE)
                .select("id, title")
                .eq("username", username)
                .like("title", f"{WORKER_TAG}%")
                .execute()
            )

            rows = result.data or []
            if not rows:
                log.info("🔍  No worker events found — nothing to delete.")
                continue

            ids = [r["id"] for r in rows]
            log.info("🗑️   Deleting %d worker event(s): %s", len(ids), ids)

            # Delete them all in one go
            del_result = (
                client.table(EVENTS_TABLE)
                .delete()
                .eq("username", username)
                .like("title", f"{WORKER_TAG}%")
                .execute()
            )

            deleted = del_result.data or []
            log.info("✅  Deleted %d event(s).", len(deleted))

        except Exception as exc:
            log.error("❌  Cleanup error: %s", exc)


# ── Entry point ────────────────────────────────────────────────────────────────

async def main() -> None:
    log.info("=" * 60)
    log.info("🦈  SHARK CALENDAR — AUTO EVENT WORKER")
    log.info("    Create interval : %d–%d min", CREATE_MIN_SEC // 60, CREATE_MAX_SEC // 60)
    log.info("    Delete interval : %d min",   DELETE_SEC // 60)
    log.info("    Target date     : %s",        FAR_DATE)
    log.info("    Worker tag      : '%s'",      WORKER_TAG)
    log.info("=" * 60)

    client, username = get_client()
    log.info("👤  Operating as user: %s", username)

    # Run both loops concurrently
    await asyncio.gather(
        creator_task(client, username),
        cleaner_task(client, username),
    )


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        log.info("\n🛑  Worker stopped.")
